name: build
on: [push, pull_request]
permissions:
  contents: read
  packages: write
env:
  IMAGE_NAME: ghcr.io/vampirebyte/rabbitmq-web-ocpp
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        PLATFORM:
          # - { RMQREF: "4.0.9", ERLVER: "26.2", ELXVER: "1.16" }
          # - { RMQREF: "4.1.8", ERLVER: "27", ELXVER: "1.18" }
          - { RMQREF: "4.2.7", ERLVER: "27", ELXVER: "1.19" }
          - { RMQREF: "4.3.1", ERLVER: "27", ELXVER: "1.19" }
    name: "Broker: ${{ matrix.PLATFORM.RMQREF }} - Erlang: ${{ matrix.PLATFORM.ERLVER }} - Elixir: ${{ matrix.PLATFORM.ELXVER }}"
    steps:
      - name: Checkout Plugin
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Set short SHA
        id: vars
        run: echo "value=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Log in to GitHub Container Registry
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build RabbitMQ image with bundled plugin
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          target: runtime

          build-contexts: |
            plugin=.

          build-args: |
            RABBITMQ_VERSION=${{ matrix.PLATFORM.RMQREF }}
            ERLANG_VERSION=${{ matrix.PLATFORM.ERLVER }}
            ELIXIR_VERSION=${{ matrix.PLATFORM.ELXVER }}

          platforms: ${{ github.ref == 'refs/heads/master' && 'linux/amd64,linux/arm64' || 'linux/amd64' }}

          outputs: |
            type=local,dest=${{ runner.temp }}/rootfs
            ${{ github.ref == 'refs/heads/master' && 'type=registry' || '' }}

          tags: |
            ${{ env.IMAGE_NAME }}:${{ matrix.PLATFORM.RMQREF }}-ocpp
            ${{ env.IMAGE_NAME }}:${{ matrix.PLATFORM.RMQREF }}-ocpp-${{ steps.vars.outputs.value }}

          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ matrix.PLATFORM.RMQREF }}-ocpp
            org.opencontainers.image.title=RabbitMQ ${{ matrix.PLATFORM.RMQREF }} with rabbitmq_web_ocpp

          cache-from: |
            type=gha,scope=rmq-${{ matrix.PLATFORM.RMQREF }}
          cache-to: |
            type=gha,mode=max,scope=rmq-${{ matrix.PLATFORM.RMQREF }}

      - name: Store build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: plugins-ocpp-rmq${{ matrix.PLATFORM.RMQREF }}-erl${{ matrix.PLATFORM.ERLVER }}-elx${{ matrix.PLATFORM.ELXVER }}-${{ steps.vars.outputs.value }}
          path: |
            ${{ runner.temp }}/rootfs/opt/rabbitmq/plugins/rabbitmq_web_ocpp-[0-9].*.ez
            ${{ runner.temp }}/rootfs/linux_amd64/opt/rabbitmq/plugins/rabbitmq_web_ocpp-[0-9].*.ez
          if-no-files-found: error
